# Generated by Django 5.0 on 2023-12-06 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa:')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo:')),
                ('ano', models.CharField(max_length=10, verbose_name='Modelo:')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carros', verbose_name='Foto:')),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFuncionario', models.CharField(max_length=254, verbose_name='Nome:')),
                ('emailFuncionario', models.EmailField(max_length=254, verbose_name='Email:')),
                ('cpfFuncionario', models.CharField(max_length=11, verbose_name='CPF:')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=254, verbose_name='Nome:')),
                ('emailCliente', models.EmailField(max_length=254, verbose_name='Email:')),
                ('cpfCliente', models.CharField(max_length=11, verbose_name='CPF:')),
                ('enderecoCliente', models.TextField(verbose_name='Endereço:')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário:')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel_carros.carro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel_carros.cliente')),
            ],
        ),
    ]
