# Generated by Django 5.0 on 2023-12-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_carros', '0002_cliente_telefonecliente_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.CharField(max_length=10, verbose_name='Ano:'),
        ),
    ]
