# Generated by Django 5.0 on 2023-12-16 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_carros', '0003_alter_carro_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
    ]
