# Generated by Django 5.0 on 2023-12-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_carros', '0006_delete_devolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('descricao_avaria', models.TextField(blank=True, null=True, verbose_name='Descrição da Avaria')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aluguel_carros.contratoaluguel')),
            ],
        ),
    ]
